import React from 'react';
import Head from 'next/head';
import AdminNavbar from '../../components/AdminNavbar';
import styles from '../../styles/Admin.module.scss'

const ItemEditor = () => {
  return (
    <div>
      <Head>
        <title>Next Shop - Manage Items</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminNavbar/>
      <main className={styles.main}>
        
      </main>
    </div>
  )
};

export default ItemEditor;
